### ISSUE TITLE
Spawn system

### ISSUE THREAD

**Issue by Razvangt** [MadCrabsTeam/mad_crabs#2]
# Spawn
## Monsters
Spawn Monsters

**Comment by ShadowCurse** [comment]
- For each wall/side there should be an enemy spawn.
  - It can be an entity with spawn attached as component. This way we can have multiple enemy spawns attached to the same entity.
- Enemies should spawn just outside the screen, so that player would not be able to see that. (Can just attach transform to the entity and use that to move spawns).
